In [10]:
import numpy as np

# assume pose_rotvec is a 2D numpy array with shape (n, m)
poses = np.random.randint(0, 10, size=(10, 6))

print(poses)

# select the first three columns of pose_rotvec


# print the resulting array
print(poses[0:2, :])

[[7 6 1 2 6 3]
 [7 7 7 7 5 9]
 [2 2 5 0 3 8]
 [3 6 8 9 2 9]
 [6 5 4 1 8 4]
 [9 7 0 5 3 8]
 [9 5 5 4 8 2]
 [4 0 6 6 9 7]
 [3 9 1 8 2 3]
 [7 0 9 6 3 1]]
[[7 6 1 2 6 3]
 [7 7 7 7 5 9]]


In [2]:
! pip install git+https://github.com/rodrigo-castellon/jukemirlib.git

import jukemirlib

audio = jukemirlib.load_audio('/Users/Marvin/NII_Code/JustLM2D/Songs_2022/JustDance2022NailsHairHipsHeelsJustDanceVersionbyTodrickHallGameplay/audio.wav')

reps = jukemirlib.extract(audio, layers=[36])

  Cloning https://github.com/rodrigo-castellon/jukemirlib.git to /private/var/folders/yj/cc8p36j97cvgvkft3_74qy840000gp/T/pip-req-build-nczshwnv
  Running command git clone --filter=blob:none --quiet https://github.com/rodrigo-castellon/jukemirlib.git /private/var/folders/yj/cc8p36j97cvgvkft3_74qy840000gp/T/pip-req-build-nczshwnv
  Resolved https://github.com/rodrigo-castellon/jukemirlib.git to commit 98223a631f7327b4b45ed60f900e6a3a71130b25
  Preparing metadata (setup.py) ... done
  Cloning https://github.com/rodrigo-castellon/jukebox.git to /private/var/folders/yj/cc8p36j97cvgvkft3_74qy840000gp/T/pip-install-9bzzyfkh/jukebox_c83b888d3f28463f9678a84cb09e0825
  Running command git clone --filter=blob:none --quiet https://github.com/rodrigo-castellon/jukebox.git /private/var/folders/yj/cc8p36j97cvgvkft3_74qy840000gp/T/pip-install-9bzzyfkh/jukebox_c83b888d3f28463f9678a84cb09e0825
  Resolved https://github.com/rodrigo-castellon/jukebox.git to commit 6b4486164e150286d9d6944797a14b19f31912f

OSError: cannot load library '/Users/Marvin/miniconda3/lib/python3.10/site-packages/_soundfile_data/libsndfile.dylib': dlopen(/Users/Marvin/miniconda3/lib/python3.10/site-packages/_soundfile_data/libsndfile.dylib, 0x0002): tried: '/Users/Marvin/miniconda3/lib/python3.10/site-packages/_soundfile_data/libsndfile.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/Marvin/miniconda3/lib/python3.10/site-packages/_soundfile_data/libsndfile.dylib' (no such file), '/Users/Marvin/miniconda3/lib/python3.10/site-packages/_soundfile_data/libsndfile.dylib' (no such file)